runtime: go
api_version: go1
default_expiration: "30m"

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /styles/(.+\.css)
  static_files: styles/\1
  upload: .+\.css

- url: /img/(.+\.png)
  static_files: img/\1
  upload: .+\.png

- url: /js/(.+\.js)
  static_files: js/\1
  upload: .+\.js

- url: /.*
  script: _go_app

