runtime: go
api_version: go1
default_expiration: "100d"

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /static/styles/(.+\.css)
  static_files: static/styles/\1
  upload: /static/styles.+\.css

- url: /static/img/(.+\.png)
  static_files: static/img/\1
  upload: /static/img/.+\.png

- url: /static/js/(.+\.js)
  static_files: static/js/\1
  upload: /static/js/.+\.js

- url: /exclusive/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app