runtime: go
api_version: go1

default_expiration: "30d"

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /styles/styles.css
  static_files: styles/styles.css
  upload: styles/styles.css

- url: /img/(.+\.png)
  static_files: img/\1
  upload: .+\.png

- url: /js/(.+\.js)
  static_files: js/\1
  upload: .+\.js

- url: /.*
  script: _go_app

